### ISSUE TITLE
Equation lables in replicate correlation plots are printed on to cloud of data

### ISSUE THREAD

**Issue by mlpedersen** [NanoCAN/HiTSeekR#4]
When looking correlation between replicates the equation labels are printed onto the data cloud making them hard to read. Moreover, if several correlation plots are displayed together some equation labels will simply be cut off.

**Comment by mlist** [comment]
Placing these labels on the text is unfortunately non-trivial. I added a checkbox that allows you to switch them off to get nicer plots. I'll think of a better solution for the future.
